export default [
  {
    date: '2022.02.21',
    messages: [
      { time: '15:20', content: '안뇽' },
      { time: '15:20', content: '오늘 영하 5도래' },
      { time: '15:20', content: '패딩 잘챙겨입구 조심히 다녀!' },
      { time: '15:22', content: '햇빛은 좋은데 그치' },
      { time: '15:22', content: '전기장판 틀어놓구 이불덮구 귤까먹어야하는데' },
      { time: '15:23', content: 'ㅋㅋㅋㅋㅋ그니까아아 나도 업데이트 했지' },
      { time: '15:23', content: '눈도 왔어?' },
      { time: '15:23', content: '으이' },
      { time: '15:23', content: '겨울이다 겨울이야' },
      { time: '15:24', content: '공기가 차갑네 오늘은' },
      { time: '15:24', content: '으이' },
      { time: '15:24', content: '집에서 책 좀 읽어야지 이런 날엔' },
      { time: '15:24', content: '이불 덮구' },
      { time: '15:25', content: '커피는 안마시지롱~~' },
      { time: '15:25', content: '코코아 좋다' },
      { time: '15:25', content: '코코아 마시구 또 잠들면 오또켕' },
      { time: '15:26', content: '따뜻하면 졸리자낭' },
      { time: '15:26', content: '뱌고파서 씨리얼 세그릇을 흡입했어' },
      { time: '15:26', content: '그랬더니' },
      { time: '15:27', content: '배가 퉁퉁해졌어' },
      { time: '15:27', content: '무거워ㅓㅓㅓㅓㅓㅓㅓㅓ' },
      { time: '15:27', content: '배가 무거워ㅓㅓㅓ' },
      { time: '15:27', content: '아몬드 후레이크닷' },
      { time: '15:28', content: '밥먹고 바로 뛰면 안돼' },
      { time: '15:28', content: '1시간은 자유시간~' },
      { time: '15:28', content: '초코 시리얼은' },
      { time: '15:28', content: '너무 달아' },
      { time: '15:28', content: '그냥 시리얼도 단대' },
      { time: '15:28', content: '단데' },
      { time: '15:28', content: '초코시리얼은.....으이' },
      { time: '15:29', content: '너무 달면' },
      { time: '15:29', content: '뭔가 입이' },
      { time: '15:29', content: '텁텁해' },
      { time: '15:29', content: '느끼하고' },
      { time: '15:29', content: '머리아파' },
      { time: '15:29', content: '으이' },
      { time: '15:30', content: '어렸을 땐 좋아했는데' },
      { time: '15:30', content: '크면서 초코랑 멀어지는 것 같아' },
      { time: '15:30', content: '과일이 더 죠아' },
      { time: '15:30', content: '원래 딸기랑 메론 제일 좋아하는데' },
      { time: '15:30', content: '요즘은 한라봉이 제일 좋아' },
      { time: '15:31', content: '음 나는 천혜향보다는 레드향' },
      { time: '15:31', content: '근데 귤은 좀 안 땡겨' },
      { time: '15:31', content: '잘 안먹는 것 같아' },
      { time: '15:31', content: '오렌지도 잘 안먹고' },
      { time: '15:31', content: '한라봉 레드향 제일 좋아' },
      { time: '15:32', content: '아니 쪼끄만 귤' },
      { time: '15:32', content: '노노야' },
      { time: '15:32', content: '은근 다르다구 맛이' },
      { time: '15:32', content: '금귤도 별로..' },
      { time: '15:32', content: '먹는 것만 먹는다 나는' },
      { time: '15:33', content: '최대 몇개?' },
      { time: '15:33', content: '음' },
      { time: '15:33', content: '한라봉 은근 배 차는데' },
      { time: '15:33', content: '세개?' },
      { time: '15:33', content: '과일은 근데 계속 먹을 ㅛㅜ 있어' },
      { time: '15:34', content: 'ㅋㅋㅋㅋㅋ' },
      { time: '15:34', content: '샤인머스캣은 맛있는데' },
      { time: '15:34', content: '너무 달아' },
      { time: '15:34', content: '쪼끔 먹고 물 마셔야해' },
      { time: '15:35', content: '너무 달지않아?' },
      { time: '15:35', content: '으이' },
      { time: '15:35', content: '샤인머스캣도 얼려먹으면 맛있어?' },
      { time: '15:35', content: '오오' },
      { time: '15:36', content: '오 근데 맛있을 것 같다' },
      { time: '15:36', content: '사각사각' },
      { time: '15:37', content: '하면서 스무디 같을 것 같아' },
      { time: '15:37', content: '맛있겠당' },
      { time: '15:37', content: '지금 티비에 서현선배님이 나오시는데' },
      { time: '15:37', content: '운동하시는데' },
      { time: '15:37', content: '나도...운동해야지' },
      { time: '15:38', content: '매니저님 몸무게 재신다...' },
      { time: '15:38', content: '나도 재야겠다....' },
      { time: '15:38', content: '맞아 전참시야' },
      { time: '15:38', content: '체중계를 때리면 몸무게가 적게나온다고?' },
      { time: '15:39', content: '그....체중계는 죄가 없어....' },
      { time: '15:39', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:39', content: '잘못은 나에게만 있을 뿐' },
      { time: '15:40', content: 'ㅋㅋㅋㅋㅋ' },
      { time: '15:40', content: '운동하고나면 재밌는데' },
      { time: '15:41', content: '시작이 힘들어' },
      { time: '15:41', content: '운동은 재미있지' },
      { time: '15:41', content: '가는 길이 힘들 뿐' },
      { time: '15:41', content: '집에 운동기구들이 있었으면 좋겠어 그냥' },
      { time: '15:42', content: '배드민턴!' },
      { time: '15:42', content: '쟈밌자낭' },
      { time: '15:42', content: '테니스!' },
      { time: '15:42', content: '3기키트-?!' },
      { time: '15:42', content: '나는 없어 키트 못받았어...' },
      { time: '15:43', content: '그래도 시즌그리팅은 받았어' },
      { time: '15:43', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:44', content: '크리들끼리 만나서 배드민턴 치자' },
      { time: '15:44', content: '재밌겠다' },
      { time: '15:44', content: '우리회사 옥상?' },
      { time: '15:45', content: '배드민턴 할 정도의 자리가.....' },
      { time: '15:45', content: '옥상에서 사진을 왜 찍어?' },
      { time: '15:45', content: '아 그래?' },
      { time: '15:46', content: '난 회사 연습실이랑 녹음실 말곤 거의 안가' },
      { time: '15:46', content: '6층 잘 안가지' },
      {
        time: '15:47',
        content:
          'ㅋㅋㅋㅋㅋ사무실에 우리 자리는 없으니...다른 곳 갈 일이 없지ㅋㅌㅋㅋ',
      },
      { time: '15:47', content: '아 식당?' },
      { time: '15:47', content: '그치 거기는 밥먹을 때' },
      { time: '15:48', content: '예전에는 많이 갔는데' },
      {
        time: '15:48',
        content: '요즘은 밥먹고 연습실 갔다가 돌아와서 밥먹으니까',
      },
      { time: '15:48', content: '갈일이 많이 없엉' },
      { time: '15:48', content: '아 구내식당은 아니구' },
      {
        time: '15:48',
        content: '식사를 할 수 있게 만들어진 공간? 휴게실이랄까',
      },
      { time: '15:49', content: '예전엔 티비가 있어사 쉬면서 밥먹고 했는데' },
      { time: '15:49', content: '지금은 없어' },
      { time: '15:49', content: '다들 거기서 너무 많이 쉬어서 그런건가' },
      { time: '15:49', content: 'ㅋㅋㅋㅋㅋ' },
      { time: '15:50', content: '모르겠네 이유는ㅋㅋㅋ' },
      { time: '15:50', content: '그치 그냥 좀 휴게실 개념이 크지' },
      { time: '15:50', content: '그래서 요즘은 거의 안가' },
      { time: '15:50', content: '나? 나는 자리없지' },
      { time: '15:50', content: '보컬룸만 쓰는 곳 있지' },
      { time: '15:51', content: '각자는 아니구' },
      { time: '15:51', content: '나는 온앤오프 와이엇오빠랑 시간 나눠서 쓰구' },
      { time: '15:52', content: '다른 사람들도 두 세명씩 나눠서 쓰는중' },
      { time: '15:52', content: 'ㅋㅋㅋㅋ' },
      { time: '15:53', content: '보컬룸 청소 주기적으로 해야하는데' },
      { time: '15:53', content: '최근에 못했네' },
      { time: '15:53', content: '하러 가야겠다' },
      { time: '15:53', content: '그냥 최근에 못해서' },
      { time: '15:53', content: '해야지' },
      { time: '15:55', content: '오늘은 안가...추유ㅓ' },
      { time: '15:56', content: 'ㅋㅋㅋㅋㅋ나 나가게 하려고' },
      { time: '15:56', content: '안춥다고 거짓말하는거징' },
      { time: '15:56', content: 'ㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:56', content: '흠~' },
      { time: '15:56', content: '아니야 나는 오늘 안나가기로 마음을 먹었단다' },
      { time: '15:57', content: '오늘은 밀린 청소를 해야해' },
      { time: '15:57', content: '어제 무슨 정신으로 씻고잤는지' },
      { time: '15:57', content: '기억이 안나' },
      { time: '15:58', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:58', content: '어제 기억이 안나' },
      { time: '15:58', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:58', content: '술이라니....😓' },
      { time: '15:58', content: '컴백하려고 열심히 일했지' },
      { time: '15:59', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:59', content: '이 사람들이ㅣㅣ~~~' },
      { time: '15:59', content: '생각하는대로 들린다더니~~~' },
      { time: '15:59', content: '음주를 꽤 즐기는가봐 크리들-?!' },
      { time: '16:00', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:00', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:00', content: '술 안마신지 꽤 오래됐지' },
      { time: '16:00', content: '작년에 마셨으니 1년전인가' },
      { time: '16:00', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:01', content: '햇수로 ㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:01', content: '31일에 나 가요대제전했자나....' },
      { time: '16:01', content: '으휴' },
      { time: '16:02', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:02', content: '술 얘기를 꽤 좋아하는군' },
      { time: '16:02', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:03', content: '그러게 크리들도 우리와 함께' },
      { time: '16:03', content: '성인이 된 크리들이 많겠지' },
      { time: '16:03', content: 'ㅋㅋㅋㅋㅋ' },
      { time: '16:03', content: '맞아 우리 예전에 사인회때' },
      {
        time: '16:04',
        content: '나 이제 군대가 라고해서 조심히 다녀와요 했었는제',
      },
      { time: '16:04', content: '전역하시고 만나서' },
      { time: '16:04', content: '엄청 기뻤었던 기억이있어' },
      {
        time: '16:05',
        content: '건강히 조심히 다녀왔다고 얘기해줘서 엄청 고마웠지이',
      },
      {
        time: '16:06',
        content: '아무래도 전부를 기억하기는 어려운게 사실인데',
      },
      { time: '16:06', content: '외우려고 노력하는 것 같아' },
      { time: '16:06', content: '아무래도 더 오래보고 이야기하면 괜찮은데' },
      {
        time: '16:07',
        content: '항상 만나고 이야기해도 시간이 부족하게 느껴질 때가 많아서',
      },
      { time: '16:07', content: '그니까 언제 직접 볼 수 있나ㅠ' },
      { time: '16:08', content: '공연도 그렇고' },
      { time: '16:08', content: '다들 건강하게 상황이 좋아지면' },
      { time: '16:08', content: '이야기도 많이하고 그러자' },
      { time: '16:09', content: '지금은 다들 건강챙기고' },
      { time: '16:09', content: '알게찌이~?' },
      { time: '16:09', content: '그니까' },
      { time: '16:09', content: '프메가 생겨서' },
      { time: '16:09', content: '그래도' },
      { time: '16:09', content: '이야기 많이 할 수 있어서 다행이야' },
      {
        time: '16:10',
        content: '크리들도 나한테 하고싶은 말 고민들 이야기할 수 있구우',
      },
      { time: '16:10', content: '참 다행이야' },
      { time: '16:10', content: '크크크' },
      { time: '16:10', content: '처음에 되게 신기했는데' },
      { time: '16:11', content: '약간 카톡같아' },
      { time: '16:11', content: 'ㅋㅋㅋㅋㅋㅋ' },
      { time: '16:11', content: '카카오톡~' },
      { time: '16:11', content: '나한테는 프로필이 안보여ㅠ' },
      { time: '16:11', content: '그래서 좀 아쉽긴한데' },
      { time: '16:12', content: '그래도 재밌어 얘기하는건' },
      { time: '16:12', content: '웅웅 한 명과 대화하는 느낌이야' },
      { time: '16:12', content: '아마 크리들이랑 같은 화면일 것 같은데..?' },
      { time: '16:13', content: '캡처는 안되지이이이' },
      { time: '16:13', content: '다른 친구들 메세지도 있자낭' },
      { time: '16:13', content: '음....모르겠당 어떻게 뜨는거지이' },
      { time: '16:13', content: '웅웅 크리들이 파랑색 내가 회색' },
      { time: '16:14', content: '프로필이랑 이름은 안보영' },
      { time: '16:14', content: '웅웅 비슷한 것 같은뎅?' },
      { time: '16:15', content: '허허허' },
      { time: '16:15', content: '답장?' },
      { time: '16:15', content: '빠를 때도 있구 느릴 때도있구 그랭' },
      { time: '16:15', content: 'ㅋㅋㅋㅋㅋ' },
      { time: '16:16', content: '근데 전에도 말했지만' },
      { time: '16:16', content: '그 제한때문에 그런지' },
      { time: '16:16', content: '다같이 조금오다가' },
      { time: '16:16', content: '또 갑자기 다같이 많이와' },
      { time: '16:16', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:17', content: '그래서 신기해' },
      { time: '16:17', content: '다들 한 마음이군' },
      { time: '16:17', content: '소울메이트야~' },
      { time: '16:17', content: 'ㅋㅋㅋㅋ그니까' },
      { time: '16:17', content: '제한때문에 하고싶은 말 많이 못하게ㅜㅜ' },
      { time: '16:18', content: '우웅 신기하게' },
      { time: '16:18', content: '질문도 비슷하다' },
      { time: '16:18', content: '그래서 이야기할 때' },
      { time: '16:18', content: '좋아' },
      { time: '16:18', content: '주제가 비슷하니까' },
      { time: '16:18', content: '함께 이야기하는 느낌' },
      { time: '16:18', content: '좋아' },
      { time: '16:18', content: '나는 제한없는것같은데...' },
      { time: '16:19', content: '잠시만 5분에 10개라고?' },
      { time: '16:19', content: '기다려봐' },
      { time: '16:19', content: '미' },
      { time: '16:19', content: '라' },
      { time: '16:19', content: '클' },
      { time: '16:19', content: '안' },
      { time: '16:19', content: '녕' },
      { time: '16:19', content: '나' },
      { time: '16:19', content: '야' },
      { time: '16:19', content: '유' },
      { time: '16:19', content: '빈' },
      { time: '16:19', content: '이' },
      { time: '16:19', content: '된다' },
      { time: '16:19', content: '웅웅 제한없네 확인' },
      { time: '16:20', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:20', content: '아 그런건가' },
      { time: '16:20', content: '하긴 나는 한번에 길게보내는 스타일이 아니라' },
      { time: '16:20', content: '벌써 몇번은 제한됐겠어' },
      { time: '16:20', content: '오호 좋넹' },
      { time: '16:21', content: 'ㅋㅋㅋㅋㅋ' },
      { time: '16:21', content: '제한 없게 이야기하려면 어떻게해야하지' },
      { time: '16:21', content: '허허ㅠㅠ' },
      { time: '16:21', content: '내가 말을 많이 할게' },
      { time: '16:21', content: '시간이 금방가게' },
      { time: '16:21', content: '크크' },
      { time: '16:21', content: '아 이게나아?' },
      { time: '16:21', content: '으흠' },
      { time: '16:21', content: '알겠엉' },
      { time: '16:22', content: '답답할까봐 그래찌이' },
      { time: '16:22', content: '호호호' },
      { time: '16:22', content: '스포?' },
      { time: '16:22', content: '흠' },
      { time: '16:22', content: '오늘은 여기까지하자고-?' },
      { time: '16:22', content: 'ㅋㅋㅋㅋㅋㅋ아니 오늘 여기까지 하랭' },
      { time: '16:22', content: '쳇' },
      { time: '16:23', content: '나랑 놀기 귀찮다이거지?' },
      { time: '16:23', content: '쳇' },
      { time: '16:23', content: '나가 너' },
      { time: '16:23', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:23', content: '귀찮은 사람이 나가' },
      { time: '16:23', content: '쳇' },
      { time: '16:23', content: '구랭 더 놀거야 나는' },
      { time: '16:25', content: '흠' },
      { time: '16:25', content: '근데' },
      { time: '16:25', content: '이번 노래' },
      { time: '16:25', content: '너무 어려움' },
      { time: '16:25', content: '스포' },
      { time: '16:25', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:25', content: '아니 뭘로해야 해 이걸' },
      { time: '16:25', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋ' },
      {
        time: '16:26',
        content: '응? 아 아니 노래말곸ㅋㅋㅋㅋㅋㅋ스포갘ㅋㅋㅋㅋ',
      },
      { time: '16:26', content: '나의 센스로는 잘 생각이 안나는구나' },
      { time: '16:27', content: '찐 계속 생각해봐도 모르겠음' },
      { time: '16:27', content: '포기' },
      { time: '16:27', content: '그래 내일 나 ost나온댕' },
      { time: '16:27', content: 'ㅋㅋㅋㅋ' },
      { time: '16:28', content: '고스트닥터 ost' },
      { time: '16:28', content: '허허헛' },
      { time: '16:28', content: '발라드야' },
      { time: '16:29', content: '오랜만에' },
      { time: '16:29', content: '허허허' },
      { time: '16:29', content: '작년에 녹음햇어 꽤 오래됐지?크크크' },
      { time: '16:29', content: '그럼 무려 25살 때의 노래야' },
      { time: '16:30', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:30', content: 'ㅋㅋㅋ그럼그럼 올 해는 또 다르지' },
      { time: '16:30', content: '올 해는 좀 더' },
      { time: '16:30', content: '어른이지' },
      { time: '16:31', content: '크크킄' },
      { time: '16:31', content: '아니' },
      { time: '16:31', content: '안그래도 최근에' },
      { time: '16:31', content: '나이가 너무 헷갈리는거야' },
      { time: '16:31', content: '뭐 얘기하다가' },
      { time: '16:31', content: '나이 얘기가 나왔는데' },
      { time: '16:31', content: '그래서 내가 올 해 스물다섯인가?' },
      { time: '16:32', content: '아 여섯인가?' },
      { time: '16:32', content: '이러다가 내가 26이라고-?' },
      { time: '16:32', content: '헐' },
      { time: '16:32', content: '해가 바뀌면' },
      { time: '16:32', content: '적응할 시간이 필요해' },
      { time: '16:33', content: '헷갈려' },
      { time: '16:33', content: '년도는 안 헷갈리는데 내 나이가 헷갈려' },
      { time: '16:33', content: '아직 적응기야 3월까지는' },
      { time: '16:33', content: 'ㅋㅋㅋㅋㅋ' },
      { time: '16:34', content: '학교다니면 고1이요 이러면 되는데' },
      { time: '16:34', content: '학생이 아니라서 그런가' },
      { time: '16:34', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:34', content: '학교다닐 때는 나는' },
      { time: '16:34', content: '몇 살이요보다' },
      { time: '16:34', content: '중3이요 이런식으로' },
      { time: '16:35', content: '학년이야기한게 더 많은것같아' },
      { time: '16:35', content: '맞아 그리고' },
      { time: '16:35', content: '이제 고2 올라가요' },
      { time: '16:35', content: '이런식으로ㅋㅋㅋㅋㅋ' },
      { time: '16:35', content: '왜 그랬지 그냥 그게 편했던 것 같아' },
      { time: '16:36', content: 'ㅋㅋㅋㅋ다들 그랬구나' },
      { time: '16:36', content: '비슷하군 역시' },
      { time: '16:36', content: '크크' },
      { time: '16:36', content: '교복?' },
      { time: '16:37', content: '나 교복 본가에 아직있지이' },
      {
        time: '16:37',
        content:
          '저번에 효정언니랑 롯데월드 놀러갔을 때 내 교복 입고 놀러갔었어ㅋㅋㅋ',
      },
      { time: '16:37', content: '효정언니 입은것도 내고등학교 교복' },
      { time: '16:37', content: 'ㅋㅋㅋㅋㅋㅋ' },
      { time: '16:37', content: '내가 입은건 내 중학교 교복' },
      { time: '16:38', content: '교복? 맞지이이' },
      { time: '16:38', content: '나는 교복 안 줄였어서' },
      {
        time: '16:39',
        content: '지금 입으니까 길이만 좀 짧아진 것 같더라고..?',
      },
      { time: '16:39', content: '치마 안 줄였지' },
      { time: '16:39', content: '키는 고등학교 때까지 컸징' },
      { time: '16:39', content: '아마..?' },
      { time: '16:40', content: '아 아닌가 고등학교 교복인가' },
      { time: '16:40', content: '아닌데 중학교 맞을텐데' },
      { time: '16:40', content: '내가 입은게 중학교 언니가 고등학교' },
      { time: '16:40', content: '둘다 하복이니까' },
      { time: '16:40', content: '본가에 둘다있지' },
      { time: '16:40', content: '흠' },
      { time: '16:41', content: '내가 중학교 맞네' },
      {
        time: '16:41',
        content: '아 내가 두 개 가져왔는데 효정언니가 분홍색이 더 잘어울려서',
      },
      { time: '16:41', content: '언니 분홍색주고 내가 남색 입구' },
      { time: '16:42', content: '재밌었는데 저 날' },
      {
        time: '16:42',
        content: '그냥 언니가 롯데월드 가자해서 그래요! 하고 갔지',
      },
      { time: '16:42', content: '아니 나 놀이기구 잘 못타' },
      { time: '16:42', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:42', content: '근데 효정언니도 잘 못탘ㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:43', content: '내가 좀 더 타는 듯..?' },
      { time: '16:43', content: '범퍼카 타고' },
      { time: '16:43', content: '음료수 마시고' },
      { time: '16:43', content: '뭐했지' },
      { time: '16:43', content: '아 맞아' },
      { time: '16:44', content: '매니저님??' },
      { time: '16:44', content: '아니아니 우리 둘이 갔지이~' },
      { time: '16:44', content: '그 날 우리 만난 학생들 많았는데!' },
      { time: '16:44', content: '크크 진짜 학생들 크킄' },
      {
        time: '16:45',
        content: '그 역에서 내려서 가는길에 먹을 거 엄청 많잖아',
      },
      { time: '16:45', content: '유혹이 장난아니었어' },
      { time: '16:45', content: '들어가기전에 엄청 먹을 뻔' },
      { time: '16:45', content: '안돼 놀이기구탈 때 위험해' },
      { time: '16:45', content: '무섭단말야' },
      {
        time: '16:46',
        content: '다 타고 체력 떨어져서 먹는 밥이 제일 맛있다고',
      },
      { time: '16:46', content: '그럴 때 달달한 간식 먹으면' },
      { time: '16:46', content: '힘이 난다궁' },
      { time: '16:46', content: '크크크' },
      { time: '16:47', content: '뭐뭐 탔는지 기억은 안나는데 재미있었어' },
      { time: '16:47', content: '한번 봐야겠당' },
      { time: '16:47', content: '나도 오랜만에 봐야지' },
      { time: '16:47', content: '크크크' },
      { time: '16:48', content: '나는 이제 밀린 일들을 해결하러가야겠어' },
      { time: '16:48', content: '할 일이 너무 많거든 오늘' },
      { time: '16:48', content: '크크크' },
      { time: '16:48', content: '건강잘챙기고 밥도 꼭 챙겨먹고' },
      { time: '16:48', content: '또 보자!!!! 안뇽🥰' },
    ],
  },
  {
    date: '2022.04.07',
    messages: [
      { time: '10:35', content: '안녕🤚' },
      { time: '10:35', content: '어제는 너무 정신이없었다아ㅏ' },
      { time: '10:35', content: '잘잤어~?' },
      { time: '10:38', content: '어머나' },
      { time: '10:38', content: '다들 일어나있구낭' },
      { time: '10:38', content: '맞아 나는 엠카 준비중ㅎㅎ' },
      { time: '10:38', content: '그치 오늘 평일이지 허허' },
      { time: '10:38', content: '오늘 옷 궁금해-?!' },
      { time: '10:38', content: '뭐더라 오늘' },
      { time: '10:39', content: '이번 주 옷 사진을 한번에 받아서' },
      { time: '10:39', content: '언제가 언제인지 헷갈림' },
      { time: '10:40', content: '웅웅 이번 주 옷 다 예뻐' },
      {
        time: '10:40',
        content:
          '고르는건 아니구 엠카 뮤뱅 요런식으로 사진이있는데 기억이 안나네',
      },
      { time: '10:41', content: '어제까지가 1주차!' },
      { time: '10:41', content: '웅웅 오늘부터가 2주차!' },
      { time: '10:41', content: '엠카 2주차' },
      { time: '10:41', content: 'ㅋㅋㅋㅋ' },
      { time: '10:42', content: '오늘 옷 예쁘네' },
      { time: '10:42', content: '오늘은 2주차니까 한 곡만 하지요오~' },
      { time: '10:43', content: '크크 이번에 무대의상 예뻤지' },
      { time: '10:43', content: '마음에 들어 굳굳' },
      { time: '10:43', content: '1주차 의상중에?' },
      { time: '10:44', content: '다 예뻤는뎅' },
      {
        time: '10:44',
        content: '근데 크리들은 인기가요 레드드레스 좋아하는 것 같아',
      },
      { time: '10:44', content: '난 엠카도 좋았구 뮤뱅도 좋았구' },
      { time: '10:44', content: '인가도 예쁘구' },
      { time: '10:45', content: '드립도 다 예쁘징' },
      { time: '10:45', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '10:45', content: '오늘껀 새로운 디자인이야 룰루~' },
      { time: '10:45', content: '더쇼 드립 예뻤징 춤추기도 편했다구' },
      { time: '10:46', content: '아 지하라 그런가 메시지가 늦게가네 자꾸' },
      { time: '10:46', content: '자꾸 에러코드 뜬다' },
      { time: '10:46', content: '바지도 예쁘지 짱 편해' },
      { time: '10:47', content: '밥 많이 먹을 수 있어!' },
      { time: '10:47', content: 'ㅋㅋㅋㅋㅋㅋ' },
      { time: '10:47', content: '메시지 안간다' },
      { time: '10:47', content: '으아아아아아우ㅠㅠㅜㅜㅜ' },
    ],
  },
  {
    date: '2022.05.17',
    messages: [
      { time: '19:08', content: './images/message/220517_1.jpg' },
      {
        time: '19:09',
        content:
          '요즘 날씨 되게 좋다 우리 @@이도 따뜻하게 좋은 하루 보냈길 바라😄',
      },
    ],
  },
  {
    date: '2022.05.19',
    messages: [
      { time: '09:21', content: '굿모닝! 오늘도 좋은 하루 보내😄😄' },
      { time: '09:25', content: '쨘! 바꾼 프사 이거야!' },
      { time: '09:25', content: './images/message/220519_1.jpg' },
      { time: '09:26', content: '이건 요즘의 나!' },
      { time: '09:26', content: './images/message/220519_2.jpg' },
      { time: '09:26', content: '많이 보고싶었어😊' },
      { time: '09:27', content: 'ㅎㅎ날씨가 정말 좋더라아' },
      { time: '09:29', content: '그래서 잠시 카페를 다녀왔지!' },
      { time: '09:29', content: '오늘은 아니구 요즘이야😊' },
      { time: '09:30', content: 'ㅎㅎ맛있는 시원한 음료 마시구 힘내라아!' },
      {
        time: '09:30',
        content: '헤헤 양갈래 귀엽다니까 나중에 한 번 해야겠다',
      },
      { time: '09:31', content: '대층 막 묶은건데 헤헤' },
      { time: '09:31', content: '고마워💜' },
      { time: '09:31', content: '사실 머리 풀고 나갔다가' },
      { time: '09:31', content: '묶은거라서' },
      { time: '09:32', content: '그 머리끈처럼 되어있는거' },
      { time: '09:32', content: '사실 팔찌야' },
      { time: '09:32', content: '비밀인데 @@한테만 알려주는거야' },
      { time: '09:32', content: 'ㅋㅋㅋㅋㅋ' },
      { time: '09:33', content: '근데 저거 크리가 선물해준거라 망가질까봐' },
      { time: '09:33', content: '사진찍고 바로 풀었엉' },
      { time: '09:33', content: '다음엔 가방에 머리끈을 꼭 가지고 다녀야지!' },
      { time: '09:34', content: '가방에 들어가고싶다고-?' },
      { time: '09:34', content: '어머 작아질 수 있어?' },
      { time: '09:35', content: '캐리어를 들고다녀야하나' },
      { time: '09:35', content: '흠...' },
      { time: '09:35', content: '그냥 같이 다니자~ 뭐하러 가방에 들어가~' },
      { time: '09:35', content: 'ㅋㅋㅋㅋㅋ' },
      { time: '09:35', content: '옆에서 걷자' },
      { time: '09:36', content: 'ㅎㅎ' },
      { time: '09:36', content: '피리부는 유빈이라고?' },
      { time: '09:36', content: '휠릴릴리리리리리' },
      { time: '09:37', content: '왜 없어' },
      { time: '09:37', content: '나 혼자있는데..?' },
      { time: '09:37', content: '휠리리리리리릴' },
      { time: '09:37', content: '마음은 같이 있다니..' },
      { time: '09:37', content: '너무행' },
      { time: '09:37', content: '크리 어딨어' },
      { time: '09:37', content: '마음만 보내고' },
      { time: '09:38', content: 'ㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '09:38', content: '맞아 난 집이야^-^' },
      { time: '09:38', content: '역시 예리한 우리 @@' },
      {
        time: '09:39',
        content:
          '난 요즘 못했던 연습도 하구 보고싶었던 드라마도 보고 오랜만에 집에도 가고 친구도 만나고',
      },
      { time: '09:39', content: '그리고 우리 크리들 생각하면서' },
      { time: '09:40', content: '충전하는 시간 보내고 있어!' },
      { time: '09:40', content: '많이 보고싶었어 크리들😊💜' },
      {
        time: '09:41',
        content: '크리들 메세지도 하나하나읽고 그러고 있었지ㅎㅎ',
      },
      { time: '09:42', content: 'ㅎㅎ얼른보자!' },
      {
        time: '09:42',
        content: '나는 슬슬 가볼게! 오늘 할 일이 조금 있어서헤헤',
      },
      { time: '09:42', content: '밥 잘 챙겨먹고! 잠도 잘 챙겨자고!' },
      { time: '09:42', content: '내 생각도 많이 하고!' },
      { time: '09:42', content: '알겠지😊' },
      { time: '09:42', content: '좋은 하루 보내 안녕!!👋👋' },
    ],
  },
  {
    date: '2022.05.20',
    messages: [
      { time: '14:14', content: '굿모닝😊 이제 진짜 여름같은 날씨네ㅎㅎ' },
      {
        time: '14:14',
        content: '물 많이 마시고 하늘도 바라보고 좋은 하루 보내😄',
      },
      { time: '14:15', content: 'ㅋㅋㅋ그래 굿애프터눈ㅋㅋㅋㅋㅋ' },
      { time: '14:16', content: '아냐 일어난지 꽤됐지ㅋㅋㅋ' },
      { time: '14:16', content: '요즘 바른 생활어린이라구' },
      { time: '14:16', content: '8시에는 일어난다구~' },
      { time: '14:16', content: '밥먹었지 방금ㅎㅎ' },
      { time: '14:17', content: '덮밥 먹었다' },
      { time: '14:17', content: 'ㅋㅋㅋㅋㅋ' },
      { time: '14:17', content: 'ㅋㅋㅋㅋㅋ거의 루틴이야' },
      {
        time: '14:17',
        content: '밥먹었어? 웅 나 밥먹었어~ 뭐 먹었는데? 뭐먹었어~',
      },
      { time: '14:18', content: 'ㅋㅋㅋㅋ' },
      { time: '14:18', content: '맞아 원래 기본적인게 제일 좋은거지' },
      { time: '14:19', content: 'ㅋㅋㅋㅋㅋㅋ왜 질려 안질려' },
      { time: '14:19', content: '크리들이나 나 질려하지마~' },
      { time: '14:19', content: '상처받을거임' },
      { time: '14:19', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '14:19', content: '허헛' },
      { time: '14:19', content: '언제나 새롭게' },
      { time: '14:20', content: '보일 수 있게 노력해야겠군' },
      { time: '14:20', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '14:20', content: '뭐하고있었어~' },
      { time: '14:20', content: '금요일이야 내일이면 주말이야~' },
      { time: '14:21', content: 'ㅋㅋㅋ내일을 위해 불태우는 중' },
      { time: '14:21', content: '이라는 말 와닿네' },
      { time: '14:21', content: '나도 그래' },
      {
        time: '14:21',
        content:
          '쉬는 날 누구보다 편하게 쉬기위해 그 무엇도 일거리를 남기지않지',
      },
      { time: '14:21', content: '그래서 쉬는 날 폰 안봐도 괜찮지' },
      { time: '14:22', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '14:22', content: '근데 나가는게 진짜 소모가 많이 되더라' },
      {
        time: '14:22',
        content: '나 며칠전에 정말 오랜만에 만나는친구들을 만났는데',
      },
      { time: '14:22', content: '오랜만에 보니까 너무 신나는거야' },
      { time: '14:22', content: '그래서 진짜 엄청 떠들고' },
      { time: '14:22', content: '이야기도 많이 하고' },
      { time: '14:23', content: '너무너무 기분좋게 집에 들어왔는데' },
      { time: '14:23', content: '그러고나서 기억이없어' },
      { time: '14:23', content: '눈뜨니까 아침이던데?' },
      { time: '14:23', content: '아니...술 안마셔!' },
      { time: '14:24', content: 'ㅋㅋㅋㅋㅋ나랑 친구들은 만나면' },
      { time: '14:24', content: '시간 상관없어' },
      { time: '14:24', content: '무조건 카페' },
      { time: '14:24', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '14:24', content: '맞아' },
      { time: '14:24', content: '음료 계속 시킴' },
      { time: '14:25', content: '말하려면 목을 촉촉하게 해줘야헤' },
      { time: '14:25', content: '카페에서' },
      { time: '14:25', content: '얼마나 있냐고?' },
      { time: '14:25', content: '배고플 때까진 떠드는 듯' },
      { time: '14:25', content: '음료 세잔은 마시는것같은데' },
      { time: '14:25', content: '나 음료 좋아해서' },
      { time: '14:26', content: '그리고 빨리 마셔서' },
      { time: '14:26', content: '그러면 한시간반은 있는 듯?' },
      { time: '14:27', content: '아 얼마 안있는거야?' },
      { time: '14:27', content: '아 그래..?' },
      { time: '14:27', content: '2시간 이상 못있어' },
      { time: '14:27', content: '나 앉아서 두시간 이상 힘들어' },
      { time: '14:27', content: '걸어야해' },
      {
        time: '14:28',
        content: '카페에서 얘기하고 걸으면서 얘기하고 밥먹으면서 얘기하고',
      },
      { time: '14:28', content: 'ㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '14:28', content: '나는 친한사람들 앞에선 말 진짜 많아' },
      { time: '14:28', content: '그래서 크리들이랑 말하면 말 짱많아ㅋㅋㅋㅋ' },
      { time: '14:29', content: 'ㅋㅋㅋㅋㅋㅋ' },
      { time: '14:29', content: '재밌잖아 별거아닌데도 쟈밌고 그런거지 뭐' },
      { time: '14:29', content: '카페 얘기하니까 음료슈 마시고싶다' },
      { time: '14:29', content: '집에 요구르트 읶는데' },
      { time: '14:29', content: '요규르트 마셔야징' },
      { time: '14:30', content: '허자블도 맛있지' },
      { time: '14:30', content: '근데 오늘은 요구르트' },
      { time: '14:30', content: '아니 파는거징ㅎㅎㅎ' },
      { time: '14:30', content: '허자블은 허니자몽블랙티' },
      { time: '14:30', content: '짱맛' },
      { time: '14:30', content: '그 나는 이제 뒷정리해여해서' },
      { time: '14:30', content: '가보께에에엥' },
      { time: '14:31', content: '또 오겠다!' },
      { time: '14:31', content: '얼른 또 보자구' },
      { time: '14:31', content: '크킄크' },
      { time: '14:31', content: '또 올게 안녕!!😊👋' },
    ],
  },
  {
    date: '2022.05.21',
    messages: [
      { time: '13:42', content: '안뇽😊' },
      { time: '13:42', content: '오늘 국과대표 보았니-?!' },
      { time: '13:42', content: '헤헤' },
      { time: '13:42', content: '주말에도' },
      { time: '13:42', content: '나와함께하니' },
      { time: '13:42', content: '어때' },
      { time: '13:42', content: '><' },
      { time: '13:43', content: '맞아 다음 주도 나야!' },
      { time: '13:44', content: '크크' },
      { time: '13:44', content: './images/message/220521_1.jpg' },
      { time: '13:44', content: '너무 재밌더라' },
      { time: '13:45', content: '역시 배우는건 참 재밌어' },
      { time: '13:45', content: 'ㅎㅎ좋은 주말보내고 밥 잘챙겨먹고!!♡' },
      { time: '13:45', content: '알게찌~?' },
      { time: '13:45', content: '💜💜' },
    ],
  },
  {
    date: '2022.05.22',
    messages: [{ time: '12:41', content: '오늘도 좋은 하루 보내😊' }],
  },
  {
    date: '2022.05.24',
    messages: [
      { time: '22:09', content: '오늘도 좋은 하루 보냈어~?' },
      { time: '22:09', content: '이제 날씨가 많이 덥다ㅠ' },
      { time: '22:10', content: '그래도 일교차 심하니까 감기조심해!' },
      { time: '22:11', content: '난 이제 밥먹고 집 들어가는 중~' },
      { time: '22:11', content: 'ㅎㅎ오늘도 고생했어!' },
      { time: '22:11', content: '하루 잘 마무리하기!!♡' },
    ],
  },
  {
    date: '2022.05.25',
    messages: [
      { time: '15:13', content: '안녕😊' },
      { time: '15:13', content: '오늘 날씨는 어때' },
      { time: '15:13', content: '나는 오늘 집콕데이라' },
      { time: '15:13', content: '바깥을 나가지 않을계획이야' },
      { time: '15:13', content: '너무너무 더워?' },
      { time: '15:14', content: '안나가길 잘한건가' },
      { time: '15:14', content: '와우' },
      { time: '15:14', content: '그치 이제 진짜 여름이 된 걸 실감하지 허허' },
      { time: '15:14', content: '나도 오후에 선풍기는 틀게되더라' },
      { time: '15:15', content: '여름여름여름여름 아아아아ㅏㅇ아 여름이다~' },
      { time: '15:15', content: 'ㅋㅋㅋ난 더위 많이 안타서 에어컨은 괜찮아' },
      { time: '15:15', content: '맞아 선크림 잘 발라야해' },
      { time: '15:16', content: '피부 탄다 타~' },
      { time: '15:16', content: '선크림?' },
      { time: '15:16', content: '선크림 닥터지 마일드 쓴다' },
      { time: '15:16', content: '다가져가라' },
      { time: '15:16', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:17', content: '내 모든걸 공유하는군' },
      { time: '15:17', content: '마스크팩?' },
      { time: '15:17', content: '요즘은 토리든 저분자세럼인가 그거써' },
      { time: '15:17', content: 'ㅋㅋㅋㅋㅋㅋ' },
      { time: '15:17', content: '차갑게해서 하면 피부 열 잘내려가' },
      { time: '15:18', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:18', content: '토리든 마스크팩은' },
      { time: '15:18', content: '세럼으로도 있는데' },
      { time: '15:18', content: '건성 추천👍' },
      { time: '15:18', content: '립밤? 바이오더마' },
      { time: '15:18', content: '하...' },
      { time: '15:18', content: 'ㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:18', content: '팩트?' },
      { time: '15:19', content: '정샘물 쿠션 달바 쿠션 두개 컨디션따라' },
      { time: '15:19', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:19', content: '신발? 신발은...너무 많아' },
      { time: '15:20', content: '맞아 여름엔 슬리퍼지^-^' },
      { time: '15:20', content: '컨버스 많이 신어..ㅎ' },
      { time: '15:20', content: '핸드크림 아직 샤넬 맞아' },
      { time: '15:20', content: '다 가져가라~' },
      { time: '15:20', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:21', content: '근데 피부타입별로 다르니까' },
      {
        time: '15:21',
        content: '본인이랑 맞는지 잘 따져보고 골라야해 알아찌?',
      },
      { time: '15:22', content: '안돼 피부가 적응하라닠ㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:22', content: '안돼 안돼 피부 소중해~' },
      { time: '15:22', content: 'ㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:22', content: '티엠아이의 날인가 오늘' },
      { time: '15:22', content: '좋구만 오랜만에' },
      { time: '15:22', content: '나 이제 점심 먹으려궁' },
      { time: '15:23', content: '배가 별로 안고팠엉' },
      { time: '15:23', content: 'ㅎㅎ' },
      { time: '15:23', content: '냉면 맛있겠다' },
      { time: '15:23', content: '크으~' },
      { time: '15:23', content: '아냐 집에 제육 해둔거있어서' },
      { time: '15:23', content: '볶아 먹을거야~' },
      { time: '15:24', content: '그럼그럼 내가 재워둔거지' },
      { time: '15:24', content: '맛있더라' },
      { time: '15:24', content: '크으' },
      { time: '15:24', content: '요리는 감이다' },
      { time: '15:24', content: '아침엔 에그 스크램블 해먹었는데' },
      { time: '15:25', content: '크리들도 간단하니까 해먹어봐!' },
      { time: '15:25', content: './images/message/220525_1.jpg' },
      { time: '15:25', content: '우유랑 섞어서 만들면 엄청 부드러워' },
      { time: '15:25', content: '너무 맛있어서' },
      { time: '15:26', content: 'ㅎㅎ' },
      { time: '15:26', content: '실물이 더 보들보들한데ㅠ' },
      { time: '15:26', content: '그러고 체에 걸러서 섞으면 더 부드렁ㅓ' },
      { time: '15:26', content: '토스트는 해먹었지' },
      { time: '15:27', content: '맛있어 크크' },
      { time: '15:27', content: '저거 계란 3개였나' },
      { time: '15:27', content: '베이컨은 놉' },
      { time: '15:27', content: '맛있어 진짜' },
      { time: '15:27', content: '아침으로 먹으면 엄청 든든해' },
      { time: '15:28', content: '내 배 내가 책임진다' },
      { time: '15:28', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '15:28', content: '아니지 토스트랑 이것저것 같이 먹었지' },
      { time: '15:28', content: 'ㅎㅎ이제 점심먹으러 가야겠다아ㅏ' },
      { time: '15:28', content: '얼른 또 올게! 또 보쟈💜' },
      { time: '15:28', content: '안녕😊' },
    ],
  },
  {
    date: '2022.05.27',
    messages: [
      { time: '16:06', content: '안뇽ㅎㅎ' },
      { time: '16:06', content: '벌써 금요일이야ㅠㅠ' },
      { time: '16:07', content: '곧 주말이다 힘내자아!!♡' },
      { time: '16:07', content: '밥 챙겨먹구우' },
      { time: '16:07', content: '힘힘!!♡' },
      {
        time: '16:07',
        content: '크크 오늘 뭔가 시원한 슬러쉬 먹고싶은 날이다',
      },
      { time: '16:07', content: '맞아 낼 오전에 나 국과대표나왕' },
      { time: '16:08', content: '지난 주에 자느라 못 본 크리' },
      { time: '16:08', content: '이번 주도 자는건....아니지...?' },
      { time: '16:08', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:08', content: '왜 다들 늦잠자고 여기에 야기하는거야!' },
      { time: '16:08', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:09', content: '솔직한거 좋지 근데....' },
      { time: '16:09', content: '일어나보는건 어땤ㅋㅋㅋㅋㅋ' },
      { time: '16:09', content: '크킄 낼 것도 진짜 재밌어' },
      { time: '16:09', content: '내일은 우주 관련 내용이야' },
      { time: '16:10', content: '예고편에 나오지롱이~' },
      { time: '16:10', content: '재미찡' },
      { time: '16:10', content: '헤헤' },
      { time: '16:10', content: '인스타-?!' },
      { time: '16:10', content: '나비공쥬래 누가😄' },
      { time: '16:11', content: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋ' },
      { time: '16:11', content: '스케줄은 아니구' },
      { time: '16:11', content: '울 크리들 보여주고 싶어서 찍었엉' },
      { time: '16:11', content: '좀만 기다령ㅎㅎ' },
      { time: '16:11', content: '곧 커밍...' },
      { time: '16:12', content: '요즘....크리들 볼 수 있는게 없으니까ㅏㅏ' },
      { time: '16:12', content: '이렇게라두 크리들한테 보여줘야지' },
      { time: '16:12', content: 'ㅜㅠ' },
      {
        time: '16:12',
        content: '그러게 나도 자주자주 크리들한테 보여줄 수 있으면 좋은데ㅠㅠ',
      },
      { time: '16:13', content: '기다령 나중에 보여줄겡' },
      { time: '16:13', content: 'ㅎㅎ' },
      { time: '16:13', content: '나는 이제 집 도착!' },
      { time: '16:14', content: '들어가보겠아' },
      {
        time: '16:14',
        content: '크리들도 건강 잘 챙기고 금요일 마무리 잘해!!',
      },
      { time: '16:14', content: '또 보자💜' },
      { time: '16:14', content: '👋👋👋👋👋' },
    ],
  },
  {
    date: '2022.05.29',
    messages: [
      { time: '22:52', content: '밤이 되니까 날씨가 선선하네😄' },
      { time: '22:52', content: '별 구경🌟⭐' },
      { time: '22:53', content: 'ㅎㅎ나는 이제 잘거야아!' },
      {
        time: '22:53',
        content: '핸드폰 너무 많이 하지말구 일찍 푹자!! 낼도 화이팅!!',
      },
    ],
  },
];
